### ISSUE TITLE
Task lists are rendered with dot if preview window is not wide enough

### ISSUE THREAD

**Issue by solarjoe** [atom/markdown-preview#538] opened 2018-05-09 09:52 UTC
- [ ] very long line very long line very long line very long line very long line

renders as 

![render](https://user-images.githubusercontent.com/10460113/39808465-492ddc68-537f-11e8-8770-0429f8042585.png)

Windows 7 64-bit
Atom 1.26.1

**Comment by rsese** [comment] 2018-05-09 22:30
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/markdown-preview/issues/282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-09 22:30 UTC
