### ISSUE TITLE
Markdown preview toggleable from HTML source / styles can leak

### ISSUE THREAD

**Issue by thedaniel** [atom/markdown-preview#346] opened 2015-11-30 14:38 UTC
Despite the readme, this can be toggled for HTML files, and apparently may include styles that can affect the rest of the editor: https://github.com/atom/atom/issues/9868

**Comment by 50Wliu** [comment] 2015-11-30 15:27
This is actually a duplicate of #276.

**Closed by 50Wliu** 2015-11-30 15:27 UTC
