### ISSUE TITLE
useGitHubStyle is not 100% accurate

### ISSUE THREAD

**Issue by gsklee** [atom/markdown-preview#302] opened 2015-09-08 06:05 UTC
Compare the screenshots:

Atom
![http://i.imgur.com/NNH3lxi.png](http://i.imgur.com/NNH3lxi.png)

GitHub
![http://i.imgur.com/LyD4qka.png](http://i.imgur.com/LyD4qka.png)

**Comment by pydolan** [comment] 2015-09-21 17:45
I also noticed that if the Atom setting "Scroll Past End" is enabled, this scrolling feature is enabled in the Markdown Previews' code blocks, even if "Use Github Style" is enabled. I suspect the fix for the above will address this issue, but probably worth confirming too.

**Comment by simurai** [comment] 2015-09-22 04:43
@pydolan The "Scroll Past End" issue is because code blocks currently use an instance of the main `atom-text-editor` which also respond to changes in the settings.

I think to make code blocks 100% GitHub style, they would need the same markup (with `pre code`) so the `.highlight` styles work. Not sure what GitHub uses for the syntax highlighting, Pygments maybe?

**Comment by simurai** [comment] 2015-09-22 04:57
The initial issue (table header being dark) seems to be caused by One dark. We could force it to be transparent when enabling "Use Github Style", but it should be fixed when #298 gets merged and One dark doesn't need any overrides.

**Closed** 2015-09-22 05:02 UTC
Labels: blocked, bug, help-wanted

**Comment by simurai** [comment] 2015-09-22 05:03
Actually, fixed it in One dark for now.
