### ISSUE TITLE
Add embedded MathJax

### ISSUE THREAD

**Issue by karan** [atom/markdown-preview#20] opened 2014-02-27 17:58 UTC
It should be able to embed MathJax within markdown. Adding this snippet on top of the document works but native support would be awesome.
```html
<style TYPE="text/css">
    code.has-jax {font: inherit; font-size: 100%; background: inherit; border: inherit;}
</style>
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [['$','$'], ['\\(','\\)']],
            skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'] // removed 'code' entry
        }
    });
    MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax(), i;
        for(i = 0; i < all.length; i += 1) {
            all[i].SourceElement().parentNode.className += ' has-jax';
        }
    });
</script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

**Comment by fikovnik** [comment] 2015-04-18 12:44
+1

**Comment by hyiltiz** [comment] 2015-06-23 03:32
Looking forward to Github and Atom to to add MathJax into standard markdown.

**Comment by leipert** [comment] 2015-09-02 00:21
Have a look into [markdown preview plus](https://atom.io/packages/markdown-preview-plus), which supports mathjax.

Disclaimer: I am a maintainer of markdown-preview-plus.

**Comment by ayberkt** [comment] 2015-11-23 05:26
+1 here

**Comment by lee-dohm** [comment] 2015-11-30 17:45
This is (now) a duplicate of https://github.com/atom/markdown-preview/issues/116. I'm closing this one in favor of the newer one because there has been significantly more discussion there. Please subscribe to https://github.com/atom/markdown-preview/issues/116 for updates.

**Closed by lee-dohm** 2015-11-30 17:45 UTC
Labels: enhancement
