### ISSUE TITLE
Markdown Preview Not Opening

### ISSUE THREAD

**Issue by brookshelley** [atom/markdown-preview#433] opened 2016-09-21 20:43 UTC
Mac OS Sierra
MacBook Pro
Atom 1.10.2

Keybinding resolver shows ctrl+shift+M = Markdown Preview.

Using the key command, nothing visibly occurs, and the same lack of result occurs when invoking the command from the shift+command+P menu.

**Comment by 50Wliu** [comment] 2016-09-22 00:49
Just to confirm... you have a `.md` file active when trying to invoke the keybinding?  And does it work in safe mode (`atom --safe`)?

**Comment by sankhadeeproy007** [comment] 2016-09-22 06:52
It does open in safe mode for me though. Is it because of one of the packages I am using?

**Comment by thomasjo** [comment] 2016-09-22 11:28
@sankhadeeproy007 Yes, that's correct. It could either be caused by a community package using the same keybinding, or it could be causing some kind of runtime error. For the latter you can try opening the _Developer Tools_ and checking if there are any errors showing up in the console tab.

To check the keybinding situation, open the keybinding resolver, invoke the keybinding and check which command is triggered.

**Comment by brookshelley** [comment] 2016-09-23 14:51
Yes to the .md file being selected.
Preview is working in safe mode. Perhaps it's NvAtom? There isn't an explicit keymap conflict, but I'll check developer tools.

**Comment by brookshelley** [comment] 2016-09-23 15:02
Not seeing anything in the console - disabled all community packages (4 of them - NvAtom,  Linter, Linter-JsonLint, NVAtom, Wordcount), and themes + syntax (Atom Material), and no dice. Any idea what else could get in the way of the Markdown preview?

**Comment by 50Wliu** [comment] 2016-09-23 20:13
@brookshelley After disabling the packages did you restart Atom?

**Comment by hasLandon** [comment] 2016-10-26 20:10
I'm also having the same problem with atom 1.11.2 on Mac OS Sierra

**Comment by Ben3eeE** [comment] 2016-12-19 11:51
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/markdown-preview/issues/433#issuecomment-249291031. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2016-12-19 11:51 UTC
Labels: more-information-needed, needs-reproduction

**Comment by taw00** [comment] 2016-12-20 10:23
When working a nvatom file... markdown preview does not seem to work. Not sure why.
Any other random .md file... works.

Even if I open the file directly, if nvatom "owns" that directory (folder) it will not render markdown for it.  Tried previewing via key-binding and through the menus. Baffling.

**Comment by taw00** [comment] 2016-12-20 14:39
**SOLUTION FOUND***
https://github.com/seongjaelee/nvatom/issues/40#issuecomment-149068451

**Comment by njfreesurfer** [comment] 2018-01-11 16:02
renaming the file by add .md fixed my problem.

**Comment by Sangeethks** [comment] 2018-02-20 04:40
For mac os its **ctrl+alt+shift+M**
