### ISSUE TITLE
Save as default name

### ISSUE THREAD

**Issue by ncxiao** [atom/markdown-preview#474] opened 2017-03-21 13:31 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Open a mark-down file, for example, abc.md
2. Use Shift-Ctrl-M to fire up mark-down preview
3. Click inside the preview window.
4. From the File menu, choose Save As

**Expected behavior:** [What you expect to happen]

In previous versions the Save As window should automatically fill in with a default name such as abc.md.html. This was a GREAT feature!

**Actual behavior:** [What actually happens]

But not it only fills in with a name of Untitled, not useful at all.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Evertime. Regardless of which project folder is used.

### Versions

0.159.6

**Comment by 50Wliu** [comment] 2017-03-21 13:42
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13978. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-03-21 13:42 UTC
