### ISSUE TITLE
CSS applied out of markdown preview document

### ISSUE THREAD

**Issue by demiurgosoft** [atom/markdown-preview#313] opened 2015-10-07 08:52 UTC
> Using Ubuntu 15.04
Atom 1.0.5
Markdown preview 0.150

Markdown preview renders html and css, in most cases this works properly (in the example below we use inline css to render paragraphs of out MD:
![capture1](https://cloud.githubusercontent.com/assets/5960567/10332316/bfc1d582-6cdc-11e5-9559-24bd730068ac.png)

However, I noticed that Markdown preview rendering affects the atom interface itself, when applying a rule like * for css format, all the atom interface is affected like shown below:
![capture2](https://cloud.githubusercontent.com/assets/5960567/10332317/bfc35808-6cdc-11e5-8fba-3daa359c8f1e.png)
(notice the red text in folders and documents name)

This bug doesn't happen when editing markdown without preview, only when markdown preview is active

**Comment by 50Wliu** [comment] 2015-10-07 11:48
This is a duplicate of #276, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-07 11:48 UTC
