### ISSUE TITLE
[Feature Request] Add support for Table Of Contents

### ISSUE THREAD

**Issue by Netherdrake** [atom/markdown-preview#332] opened 2015-11-07 11:07 UTC
Suppose I have a TOC like this in my markdown file.

```
- [Wish-list](#wish-list)
	- [Goals](#goals)
	- [Skills](#skills)
	- [Personal Improvement](#personal-improvement)
	- [Life](#life)
	- [Core Portfolio](#core-portfolio)
	- [Love yourself.](#love-yourself)
	- [Empowerment](#empowerment)
	- [Stop Procrastination](#stop-procrastination)
```

Can you please make it work in preview, so that when I click on the link, I get to that section of the page?

Thanks

**Comment by thomasjo** [comment] 2015-11-07 11:38
This is a duplicate of #136. Please add your comment to that thread instead.

**Closed by thomasjo** 2015-11-07 11:38 UTC
