### ISSUE TITLE
Valid Links Ending with `)` right round bracket rendered improperly

### ISSUE THREAD

**Issue by cdaringe** [atom/markdown-preview#382] opened 2016-03-12 17:19 UTC
`[stream](https://en.wikipedia.org/wiki/Stream_(computing))`

renders

`stream)`

the `)` should not be visible in the rendered output.

**Comment by 50Wliu** [comment] 2016-03-12 20:54
This is a duplicate of #374 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-12 20:54 UTC
