### ISSUE TITLE
Feature Request: Auto Scroll

### ISSUE THREAD

**Issue by jasenc** [atom/markdown-preview#297] opened 2015-08-31 03:50 UTC
I doubt this belongs here but I don't know where else to put it. 

I don't know how crazy of a task it would be to implement having the preview pane be scroll locked to the markdown file but I think that would be a great feature. I'm not sure how much help I could be but I'm more than willing to help out if someone could get me pointed in the right direction.

**Comment by mnquintana** [comment] 2015-08-31 04:18
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/markdown-preview/issues/24 though – please subscribe there for updates.

**Closed by mnquintana** 2015-08-31 04:18 UTC
