### ISSUE TITLE
When previewing on real-time loses focus

### ISSUE THREAD

**Issue by ponyesteves** [atom/markdown-preview#412] opened 2016-08-05 21:55 UTC
Hi, 
     I'm informing this cause it maybe a bug, if not it could be an enhacement. 

When previewing, while writing the MD file, it doesn't keep track on the preview of the line you are writing. The first image shows md file and preview at same line. Second image is  taken after adding a new char and it show that preview image focus on the middle of the document aprox.   

![image](https://cloud.githubusercontent.com/assets/4960589/17451481/97fa0600-5b3d-11e6-855d-c352a42914fe.png)
![image](https://cloud.githubusercontent.com/assets/4960589/17451553/1bb52e52-5b3e-11e6-9324-029e1f7f5e7e.png)

**Comment by janoj** [comment] 2016-08-09 08:11
I have the same problem, but it seems to be happening only if there are some code blocks in a document and the preview is scrolled pass the beginning of a first block.

**Comment by lee-dohm** [comment] 2016-08-11 22:35
This is a duplicate of https://github.com/atom/markdown-preview/issues/24. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-08-11 22:35 UTC
