### ISSUE TITLE
Single line code blocks collapsing

### ISSUE THREAD

**Issue by michaelklotz** [atom/markdown-preview#234] opened 2015-04-02 15:24 UTC
In the markdown preview window, a single line code block is being collapsed so it is not visible.  Unless a line break is added within the code, the code is not visible in the generated  `<pre>` block.

**Actual Behavior**
![actual](https://cloud.githubusercontent.com/assets/3826859/6967014/4b27a5e2-d922-11e4-932a-e9d8394017bf.PNG)

**Expected Behavior**
![expected](https://cloud.githubusercontent.com/assets/3826859/6967015/4b2838ea-d922-11e4-8ffb-d8a37ac07122.PNG)

**Comment by tlindsay** [comment] 2015-07-14 19:06
+1

**Comment by simurai** [comment] 2015-08-19 05:09
This seems to be the same issue as #286. The scrollbar is covering the single line.

**Comment by mattbell87** [comment] 2015-10-12 05:54
+1, This behaviour also happens on Linux and OSB builds.

**Comment by akras14** [comment] 2015-12-18 23:39
+1

**Comment by 50Wliu** [comment] 2017-10-26 17:32
Closing as a duplicate of #286.

**Closed by 50Wliu** 2017-10-26 17:32 UTC
Labels: bug
