### ISSUE TITLE
Saving as HTML doesn't save output file

### ISSUE THREAD

**Issue by michalbielejewski** [atom/markdown-preview#524] opened 2018-01-13 15:33 UTC
**Prerequisites**
* [x] Can you reproduce the problem in safe mode?
* [x] Are you running the latest version of Atom?
* [x] Did you check the debugging guide?

**Atom:** 1.24.0-beta3 x64
**OS**: Windows 10 

**Steps to Reproduce**
1. Open a Markdown file, or create new
2. Ctrl + Shift + M
3. Context Menu -> Save as HTML...
4. Select file
5. Click Save

**Expected behavior**: HTML file get saved and opened in new pane in Atom
**Actual behavior**: Files is not saved nor opened, nothing is happening actually

I've tried:
* Checking the DevTools console
* Deleting `.atom` folder
* Disabling all not built-in packages
* Running Atom in safe mode

**Versions**
```
Atom    : 1.24.0-beta3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
![bug](https://user-images.githubusercontent.com/11682584/34907376-e025c94e-f87d-11e7-90b1-8394bb6fbdce.gif)

**Comment by Ben3eeE** [comment] 2018-01-15 14:20
I can reproduce this using Atom 1.24.0-beta3. Nothing is happening when saying the save.

**Comment by 50Wliu** [comment] 2018-01-24 15:54
I can't reproduce this on 1.25.0-dev-27361fd97.  @Ben3eeE were you able to reproduce this on master, or just 1.24?

**Comment by Ben3eeE** [comment] 2018-01-24 16:17
Reproduces on 1.25.0-dev-c100ad010 for me.

**Comment by Ben3eeE** [comment] 2018-01-24 16:26
The reason I can't on 1.25.0-dev-c100ad010 is because of https://github.com/atom/atom/issues/16581. If I disable tree-sitter I can't reproduce on 1.25.

**Comment by Ben3eeE** [comment] 2018-01-24 16:34
Does not reproduce on 1.23.3. I don't have beta installed to check there again.

**Comment by daviwil** [comment] 2018-02-07 22:28
This will be fixed in 1.24.0 stable thanks to markdown-preview 0.159.20!

**Closed by daviwil** 2018-02-07 22:28 UTC
Labels: bug, triaged

**Comment by SebDeclercq** [comment] 2018-11-13 15:03
The problem seems to be back ; I can reproduce it on 1.32.2.

Versions:

```
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by rsese** [comment] 2018-11-14 19:15
Thanks @SebDeclercq - if you can reproduce in safe mode, can you open a new issue and fill out the issue template so we can take a look?

**Comment by bacc** [comment] 2018-12-15 19:43
I'm having the same issue on Mac OS 10.14.1 with Atom 1.33.0 even on Markdown files that do *not* have fenced code blocks. My source does have indented code blocks in it but none that are fenced. I can reproduce the issue in safe mode as well.

**Comment by Rob-Echlin-Solace** [comment] 2019-01-03 19:54
Repropducing this on Atom 1.33.1 x64, Windows 10.

I have a file that works fine, no fenced code blocks.

In the file that fails, I have 2 fenced code blocks, each inside a nested unnumbered list.

Example:
<pre>
* Edit a credentials file.
  * Username followed by '@' + the name of the Windows Domain (@kan)
  * ```
username=rechlin@kan
password=SuperSecretBlarney954
```
  * `/home/you/.smbcredentials`
</pre>

**Comment by petrdvorak** [comment] 2019-04-11 18:51
@daviwil Could you please reopen the issue? "Save as HTML" does not do anything.

**Comment by tpohlscheidt** [comment] 2019-05-29 07:01
Reproducable on **Atom 1.36.0**: as soon as the md file contains a fenced code block, `Save as HTML` and `Copy HTML` fail. `Inline code` does not seem to be affected.

Seconding: @daviwil could you reopen this, please?

**Comment by 50Wliu** [comment] 2019-05-29 13:51
@tpohlscheidt your issue is being tracked in #552.

**Comment by Arcanemagus** [comment] 2019-05-29 18:31
The issue discussed here has been fixed, if you are experiencing similar symptoms currently please either follow an existing issue (such as #552), or file a new issue making sure you fill out the template so we have the required information.

Thanks!
