### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

### ISSUE THREAD

**Issue by emdoubleusmyf** [atom/markdown-preview#204] opened 2015-02-22 19:08 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.9.5
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.134.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

```
At fs.js:574

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:136:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/renderer.js:8:13)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/renderer.js:190:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:20:14)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:383:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at isMarkdownPreviewView (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/main.js:20:29)
  at Object.module.exports.toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/main.js:112:11)
  at atom-workspace.atom.commands.add.markdown-preview:toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/main.js:58:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -1:12.7 markdown-preview:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:02.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-seti-ui)
  4x -0:59.9 markdown-preview:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "seti-ui",
      "monokai"
    ]
  },
  "markdown-preview": {
    "grammars": [
      "source.gfm",
      "source.litcoffee",
      "text.plain",
      "text.plain.null-grammar"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
autoclose-html, v0.15.0
autocomplete-plus, v2.1.6
color-picker, v1.4.4
dash, v1.0.2
javascript-snippets, v1.0.0
linter, v0.11.1
monokai, v0.12.0
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-02-22 21:32
Duplicate of atom/release-notes#29.

**Closed by 50Wliu** 2015-02-22 21:32 UTC

**Comment by zjunothing** [comment] 2015-03-13 01:27
m
