### ISSUE TITLE
Code snippet renders fine in Markdown Preview but appears broken on GitHub

### ISSUE THREAD

**Issue by MatthewDG** [atom/markdown-preview#473] opened 2017-03-20 23:06 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I start a code snippet one line underneath an HTML tag, Markdown Preview renders the snippet fine. (first screenshot) However, the snippet is broken on GitHub. (second screenshot) I reproduced this behavior with a snippet underneath HTML tags, so it’s not just happening with <img> tags.

Nothing breaks when a snippet is directly underneath Markdown syntax, so it should just be happening with HTML tags.

### Reproducing this bug

Place a code snippet underneath an HTML tag into a Markdown file and open Markdown Preview like the following. Add a line break after `javascript` and before the second set of ticks. The snippet will appear broken here on Github but renders fine in Markdown Preview

<h5>Test</h5>
```javascript
  console.log("test")
```

### Screenshots
<img width="1255" alt="screen shot 2017-03-20 at 6 29 24 pm" src="https://cloud.githubusercontent.com/assets/21087163/24125143/7044a814-0d9d-11e7-8f6b-c4ab9c782a32.png">

<img width="783" alt="screen shot 2017-03-20 at 6 30 32 pm" src="https://cloud.githubusercontent.com/assets/21087163/24125144/70469782-0d9d-11e7-8395-a9d99408d4d2.png">

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.10.1

### Additional Information

Thank you for reading!

**Comment by rsese** [comment] 2017-03-23 21:33
Hey @MatthewDG 👋  - I think this is basically a duplicate of https://github.com/atom/markdown-preview/issues/342?  Basically the idea that the Markdown rendering doesn't always match github.com.

I'll go ahead and close as a dupe for now and you can subscribe there for updates, but if I mis-understood anything, please let me know.

**Closed by rsese** 2017-03-23 21:33 UTC
