### ISSUE TITLE
Support for opening linked document when clicking link in markdown preview? 

### ISSUE THREAD

**Issue by breschke** [atom/markdown-preview#288] opened 2015-08-14 17:09 UTC
I'd like to be able to write (relative) links to files and open these files in Atom by clicking links in the markdown preview.

**Comment by serena-ahuja** [comment] 2015-08-14 20:38
I initially had the same question as you! I figured out that it **is possible** to write relative intra-file links  in Atom. The links don't work in Atom markdown preview, but they do work on GitHub.com.

**This is an example of what I wrote to create a relative link:**

I wanted my relative link to go to a specific header called
```
## My Header
```
The header is automatically given the anchor
```
#my-header
```
*(note that all of the uppercase characters have changed to lowercase)*

To create a link that will go to the header, I used the anchor and did this:
```
Take me [to the header](#my-header)
```
Now the text *"to the header"* is hyperlinked and when it is clicked, the webpage jumps straight to the header that I specified!

I have confirmed that there is an issue in markdown preview, but this should be a temporary work around for now.

Hope this was helpful! :)

**Comment by drorata** [comment] 2017-06-14 13:46
Is there a change on this front? Can I follow links to other MD files from within the preview?

**Comment by jonadem** [comment] 2017-06-23 07:50
Seems like a duplicate of #85

**Comment by rsese** [comment] 2017-06-23 17:41
Thanks @jonadem ✌️ closing as a dupe of #85.

Since the issue is still open @drorata, there's no news - I haven't tried it but a community package (https://atom.io/packages/markdown-preview-enhanced) that has this functionality was mentioned in the issue.

**Closed by rsese** 2017-06-23 17:41 UTC
