### ISSUE TITLE
Save-As HTML produce absolute paths to images

### ISSUE THREAD

**Issue by AubinMahe** [atom/markdown-preview#493] opened 2017-08-09 12:09 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Save-As HTML produce absolute paths to images.
Relatives and web path will be better.

### Steps to Reproduce

1. create a .md file with this text in it:

       ![description](image.png)

2. show the markdown preview
3. right-click and save as html in the same place than image.png

**Expected behavior:** [What you expect to happen]

     <img src="image.png" alt="description" />

**Actual behavior:** [What actually happens]

     <img src="C:\dir1\dir2\dir3\image.png" alt="description">

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

1.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rohitpaul** [comment] 2018-02-13 16:37
Would like to see this fixed. Work around is to edit the html and remove the absolute path using find and replace.

**Comment by ChrisGPen** [comment] 2018-02-28 20:40
I get the same results with the following .md file code:
```
<div>
<img src={require('./journal.png')} alt="introduction" />
</div>
```
result in markdown-preview using copy html:

```
 <div><br><img alt="introduction" src="/home/chris/rdwysiwyg/src/{require('./journal.png')}"><br></div>
```

also, the img closing  /  is missing.

I also tried markdown-preview-plus  with same results.

I appreciate any assistance as the edit html workaround is not very useful in my situation.

**Comment by ShadowLNC** [comment] 2018-09-09 11:05
I think this might be the same as #146.

**Comment by rsese** [comment] 2018-09-10 19:34
Thanks @ShadowLNC :+1:  Going to close as a duplicate of #146, folks can subscribe there if you'd like.

**Closed by rsese** 2018-09-10 19:34 UTC
Labels: enhancement
