### ISSUE TITLE
ctrl-shift-m not working - how to view rendered md?

### ISSUE THREAD

**Issue by magick93** [atom/markdown-preview#504] opened 2017-10-10 00:44 UTC
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am unable to view rendered markdown.
### Steps to Reproduce

1. Install markdown-preview
2. open .md file
3. hit `ctrl-shift-m`

**Expected behavior:** [What you expect to happen]

I expect to see the rendered markdown

**Actual behavior:** [What actually happens]
Nothing

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime

### Versions
tom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2017-10-10 05:24
Can you share a screenshot of what you see with <kbd>ctrl-shift-m</kbd> with the keybinding resolver enabled?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings

**Comment by magick93** [comment] 2017-10-10 05:30
Hi @rsese , sure here it is:

![selection_081](https://user-images.githubusercontent.com/2173213/31370665-14506484-ade9-11e7-8489-b387d1c049bb.png)

**Comment by Ben3eeE** [comment] 2017-10-10 11:14
> Atom : 1.15.0

Can you try upgrading to the latest version and see if that fixes the issue? Atom 1.15 is very old.

Also please try in safe mode `atom --safe`. From your keybinding-resolver it seems that you have markdown-preview-plus installed. So it might be an issue with that package and not with markdown-preview.

**Comment by justintien** [comment] 2017-10-16 10:06
I also got this issue... headache

**Comment by Ben3eeE** [comment] 2017-10-16 10:44
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/markdown-preview/issues/504#issuecomment-335440118. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

---

@justintien If you can reproduce using the latest version of Atom in safe mode `atom --safe` then please open a new issue and completely fill out the required issue template. Also include a screenshot of the keybinding-resolver when you press `ctrl-shift-m` in safe mode and we can take a look.

**Closed by Ben3eeE** 2017-10-16 10:44 UTC
Labels: more-information-needed

**Comment by justintien** [comment] 2017-10-17 01:25
@Ben3eeE Sorry for late response, I already resolved.

The reason is emmet conflict ctrl-shift-m and override it.

I modify keybindings, added
```
'.editor:not(.mini)':
    'ctrl-shift-M': 'markdown-preview:toggle'
```

it's work fine.

**Comment by JonSn0w** [comment] 2017-10-17 02:19
FWIW the command palette (<kbd>Ctrl-Shift-P</kbd>) can also be used to open the markdown preview in the event of the default keybinding getting overridden by another package.

**Comment by Kagerjay** [comment] 2018-05-24 19:58
Emmet overrode mine as well

This is how I debugged it

1. Press `CTRL+.` to see what keyboard commands do in console
2. Press `CTRL+SHIFT+M` to see which app is overriding. In my case, it was emmet

Once you find it

1. <kbd> CTRL+P</kbd>
2. Type "keymap" press  <kbd>enter</kbd>

Put this below. I used markdown-preview-plus, which also comes with LaTeX math support as well

```
'.editor:not(.mini)':
    'ctrl-shift-M': 'markdown-preview-plus:toggle'
```

Save and it should work

**Comment by lmbailey1974** [comment] 2018-12-24 19:50
I have been trying for 3 hours to render MathML in 3 different HTML previewers. It's not in MathJax, or Latex (although, I wish it was). It's in MathML. For example, 
  <math xmlns="http://www.w3.org/1998/Math/MathML"><msqrt><mn>36</mn></msqrt></math>
just shows up as "36". 
and 
<math xmlns="http://www.w3.org/1998/Math/MathML"><msup><mi>z</mi><mn>2</mn></msup><mo>&#xA0;</mo><mo>=</mo><mo>&#xA0;</mo><mn>36</mn></math>
shows up as 
z2=36

I am a few months old at html and ATOM, so I may be asking an incredibly basic question, but do I need to add some "stylesheet" or script to make any of the html preview packages render the math in my document?

**Comment by 50Wliu** [comment] 2018-12-27 00:45
@lmbailey1974 you'll probably have more luck asking on [Discuss](https://discuss.atom.io), the official Atom message board.

**Comment by latimeks** [comment] 2019-03-13 04:21
I had the same issue, to resolve it I did the following:
- `ctrl + ,`  to open settings
- click `keybindings`
- enter `markdown-preview`
- click the toggle command, then click copy
- Right under keybindings at the top there's the line `You can override these keybindings by copying and pasting them into your keymap file` click the `keymap file` part
- Paste command at the bottom and save
- open markdown file and try hotkey and it worked

I have Atom v.1.35
