### ISSUE TITLE
Does not work on the Yosemite (Mac OS X)!

### ISSUE THREAD

**Issue by iyerland** [atom/markdown-preview#280] opened 2015-07-22 17:09 UTC
ctrl-shift-m does not work!

**Comment by mnquintana** [comment] 2015-07-22 17:26
I can't reproduce this on Yosemite. We're going to need a lot [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) here. What version of Atom are you using? Can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? (`atom --safe`)

**Comment by iyerland** [comment] 2015-07-22 18:52
Atom Version: 1.0.2
The markdown preview works in safe mode. Attached image in safe mode.
![atom_safemode_markdown](https://cloud.githubusercontent.com/assets/896628/8834264/2bc73ac6-3081-11e5-97b9-da52a29a8c8d.png)
But does not work in non-safe mode.

**Comment by mnquintana** [comment] 2015-07-22 19:01
Thanks for the update! If it works in safe mode, then this means that either a community package you have installed or your [init script](https://atom.io/docs/latest/hacking-atom-the-init-file) is the culprit. You can find out by selectively enabling / disabling packages until Markdown Preview works again. Since this isn't an issue with markdown-preview, I'm going to close this out.

**Closed by mnquintana** 2015-07-22 19:01 UTC
Labels: more-information-needed

**Comment by iyerland** [comment] 2015-07-23 10:23
My init script is empty. Disabled "Emmet" package and it worked!

**Comment by pitops** [comment] 2015-08-09 14:41
then what you suggest is not use emmet?
