### ISSUE TITLE
Hyphens are not treated as bullets

### ISSUE THREAD

**Issue by driskell** [atom/markdown-preview#105] opened 2014-07-11 08:08 UTC
I used [doctoc](https://github.com/thlorenz/doctoc) to create some table of contents and it uses hyphens in the markdown.

Atom IO however does not treat them as bullets and displays them as a long string of text.

**Comment by kevinsawicki** [comment] 2015-07-31 16:15
This appears to have been resolved somehow since it was reported, I'm no longer able to reproduce.

I'm going to close this out but please comment if you still see it happening on Atom 1.0.3+.

<img width="830" alt="screen shot 2015-07-31 at 9 14 20 am" src="https://cloud.githubusercontent.com/assets/671378/9011809/9e161f2c-3764-11e5-97e5-8954727ae80d.png">

**Closed by kevinsawicki** 2015-07-31 16:15 UTC
Labels: bug
