### ISSUE TITLE
[feature-request] Open mardown-preview only on .md files and hide when switching to other file types

### ISSUE THREAD

**Issue by damianobarbati** [atom/markdown-preview#535] opened 2018-04-18 09:04 UTC
### Description
Would it be possible to have the markdown-preview automatically open when an .md file is currently viewed?
Thus hiding it when switching to another tab which is not a markdown.

**Comment by rsese** [comment] 2018-04-18 17:46
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/markdown-preview/issues/423 so you can subscribe there if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-18 17:46 UTC
