### ISSUE TITLE
List checkbox preview incorrect :(

### ISSUE THREAD

**Issue by axklim** [atom/markdown-preview#497] opened 2017-09-04 12:44 UTC
OC: windows 10

Incorect:
![bug_chekbox](https://user-images.githubusercontent.com/12901433/30027046-ec7f4de4-9187-11e7-8340-e97bdcc27c5e.png)

Normal:
![chekbox](https://user-images.githubusercontent.com/12901433/30027047-ec81a4ea-9187-11e7-9df6-c7cf8a7321d7.png)

**Comment by thomasjo** [comment] 2017-09-05 06:23
Duplicate of #282

**Closed by thomasjo** 2017-09-05 06:23 UTC
