### ISSUE TITLE
GFM Todo item bullet point misaligned with long lines

### ISSUE THREAD

**Issue by dracodoc** [atom/markdown-preview#327] opened 2015-11-04 01:13 UTC
If a GFM Todo line is wider than the preview window, the bullet point was shown on the last line of item instead of before the check box.

1. The correct way when the line is not too long
![1](https://cloud.githubusercontent.com/assets/1730496/10926660/43d53a7c-8267-11e5-8f76-f915cf8ba974.png)
2. When the line is wider, bullet point dropped to the last line
![2](https://cloud.githubusercontent.com/assets/1730496/10926668/53044c36-8267-11e5-8b12-3d04d57fc7c0.png)

**Comment by izuzak** [comment] 2015-11-04 07:53
Thanks for the report, @dracodoc -- this seems to be a duplicate of https://github.com/atom/markdown-preview/issues/142 so I'm going to close this in favor of that issue. :v:

**Closed by izuzak** 2015-11-04 07:53 UTC
