### ISSUE TITLE
Two spaces for soft break are not preserved

### ISSUE THREAD

**Issue by knzudgt** [atom/markdown-preview#480] opened 2017-04-02 12:47 UTC
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

At GitHub a single newline character cause a line break, and this can be set in Atom too.
However a general rule for markdown is that a soft break can be created by adding two spaces _after_ the end of a line and _before_ a new line break. These two spaces are automatically deleted by Atom whenever the buffer is saved to disk.

### Steps to Reproduce

1. Uncheck  `Break On Single Newline` in markdown-preview setting
2. Write a line, add two spaces + a single line break
3. Write a new line
4. Save buffer to disk with ctrl + s

**Expected behavior:** [What you expect to happen]

A single line break (soft break)

**Actual behavior:** [What actually happens]

Atom would render the two lines simply as a single straight line.
Check the end of the first line: Atom deletes the two spaces

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

Atom : 1.15.0
Electron: 1.3.13
Chrome : 52.0.2743.82
Node : 6.5.0

apm 1.15.3
npm 3.10.5
node 4.4.5 x64
python 2.7.6
git 2.11.0

OS: Ubuntu 14.04 LTS

**Comment by rsese** [comment] 2017-04-03 18:26
@knzudgt do you have `Keep Markdown Line Break Whitespace` enabled in the whitespace package?

**Comment by knzudgt** [comment] 2017-04-05 10:28
@rsese Yes, it is enabled

**Comment by rsese** [comment] 2017-04-07 05:04
Hmmm, with that setting enabled, I can't reproduce with your steps:

![md-newline](https://cloud.githubusercontent.com/assets/734194/24786208/33d5a6ae-1b25-11e7-9c6d-85e68c6520e3.gif)

I have invisibles showing and with `Keep Markdown Line Break Whitespace` enabled, I can see the 2 space characters are preserved.  Are you doing anything differently or am I mis-understanding anything?

**Comment by Ben3eeE** [comment] 2017-04-07 06:47
Hey @knzudgt,

I have some additional questions to help narrow this down.

* Do you have the `language-gfm` package enabled?
* Is the language of the file you are saving set to `GitHub Markdown`? You can see the language in the bottom right corner on the status bar.

It has been reported in https://github.com/atom/whitespace/issues/137 that this setting only seems to work if the language is set to `GitHub Markdown`.

**Comment by knzudgt** [comment] 2017-04-08 18:49
@Ben3eeE good guess!
In effect I disabled the `language-gfm` package because of the reasons explained in Atom's issue [#14058](https://github.com/atom/atom/issues/14058).
In few words, I am writing a documentation on Ruby on Rails. In Rails `partials` (chunks of html.erb code that can be rendered in html.erb documents) are named starting with an underscore. 

In markdown underscore can introduce a text in italics, but only if that text is enclosed by two underscores, that is if it has also another underscore in the end.

The `language-gfm` package package is really horrible to use in this context, because it start treating all text following an underscore as italics. It should not. The result is that, if I write something like _partial.html.erb, `language-gfm` would turn pink and italics all the text following the underscore. My words would look pink and italics from the underscore to this point.

So I had to disable it.

**Comment by Ben3eeE** [comment] 2017-04-11 09:55
@knzudgt Thanks for reporting back :bowing_man: It looks like this is a duplicate of https://github.com/atom/whitespace/issues/137 so I am going to close this issue. But let me know if there is something I am misunderstanding and you see this issue even with `language-gfm` enabled and we will reopen and investigate more :sparkles:

**Closed by Ben3eeE** 2017-04-11 09:55 UTC
Labels: needs-reproduction
