### ISSUE TITLE
URLs with parentheses are rendered incorrectly

### ISSUE THREAD

**Issue by marco-brandizi** [atom/markdown-preview#407] opened 2016-07-06 10:03 UTC
For instance, this: `[dbpres:Orion_(mythology)](http://dbpedia.org/resource/Orion_(mythology))` is rendered as `dbpres:Orion_(mythology)) `, while in GitHub it is correctly shown as `dbpres:Orion_(mythology)`, as I can show you even in the text of this comment: [dbpres:Orion_(mythology)](http://dbpedia.org/resource/Orion_(mythology)).

**Comment by 50Wliu** [comment] 2016-07-15 12:00
This is a duplicate of #374 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-15 12:00 UTC
