### ISSUE TITLE
New tabs open at the right side

### ISSUE THREAD

**Issue by turhn** [atom/markdown-preview#132] opened 2014-09-04 01:55 UTC
When Markdown Preview is open and selected, new tabs are added to the preview's section.

**Situation** :
![screen shot 2014-09-04 at 04 41 28](https://cloud.githubusercontent.com/assets/4946775/4143929/b9efa3b0-33d4-11e4-8ccf-8e2880baf530.png)

**Expected** :
![screen shot 2014-09-04 at 04 42 01](https://cloud.githubusercontent.com/assets/4946775/4143932/c49ac754-33d4-11e4-97af-66e1d88f13f0.png)

I think only new preview tabs shouldn't be added to previews' splitted section. Just to be more clear, all raw markdowns and other file types are on the left and all markdown previews are on the right.

**Comment by aleksandar-todorovic** [comment] 2015-01-27 23:57
I have to agree that this _is_ annoying a lot, but I don't think it is designed to be any kind of a special window, it's just designed to split your window in half, and that's just a usual behaviour when you split your window.

**Comment by thedaniel** [comment] 2015-01-28 00:01
Yep, what @aleksandar-todorovic said is true. markdown-preview doesn't have any special control over which half of the split is focused or anything. Perhaps if someday the preview becomes special kind of pane we could address this behavior but I think I will close this one as 'working as intended' for now.

**Closed by thedaniel** 2015-01-28 00:01 UTC
