### ISSUE TITLE
Inlined CSS styles in MD files leak to the whole editor

### ISSUE THREAD

**Issue by gamell** [atom/markdown-preview#408] opened 2016-07-16 04:30 UTC
When I inline some `<style>` tags in my markdown file - AFAIK inlining HTML is valid Markdown in many flavors - the styles added there will **leak** to the whole editor instead of being applied only to the markdown preview panel. 

See attached screenshot.

System info:

Mac OSX 10.11.5

```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

![github-markdown-preview](https://cloud.githubusercontent.com/assets/2460215/16892765/5f86ac26-4ad3-11e6-82bd-29eb4e0dee57.png)

**Comment by 50Wliu** [comment] 2016-07-16 10:50
This is a duplicate of #276 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-16 10:50 UTC
Labels: enhancement

**Comment by gamell** [comment] 2016-07-18 01:47
@50Wliu sorry I couldn't find the original. Thanks for pointing me to it!
