### ISSUE TITLE
Syncing with Tab Changes

### ISSUE THREAD

**Issue by Tamriel** [atom/markdown-preview#345] opened 2015-11-29 21:37 UTC
Like https://github.com/Glavin001/atom-coffeescript-preview/issues/3

**Comment by lee-dohm** [comment] 2015-11-30 17:38
This appears to be a duplicate of https://github.com/atom/markdown-preview/issues/160. Please let us know if this is not the case.

**Closed by lee-dohm** 2015-11-30 17:38 UTC
