### ISSUE TITLE
Markdown preview only appears when clicking directly on text

### ISSUE THREAD

**Issue by Anon-Penguin** [atom/markdown-preview#356] opened 2015-12-26 00:56 UTC
The markdown preview option in the context menu only appears when clicking on the filename directly, not the area to the left or the right of it.

I am using 1.3.2 on Windows 10.

I highlighted the area that the context menu appears with the markdown preview option—

![2015-12-25 18_52_06-settings - c__users_matth_dropbox_github_golang - atom](https://cloud.githubusercontent.com/assets/7022869/12004743/b485466e-ab38-11e5-9919-66e3a0815a90.png)

Comparison of context menus:

![2015-12-25 18_54_53-settings - c__users_matth_dropbox_github_golang - atom](https://cloud.githubusercontent.com/assets/7022869/12004751/2f7dc120-ab39-11e5-8907-c6718ea4e045.png)

![2015-12-25 18_55_08-settings - c__users_matth_dropbox_github_golang - atom](https://cloud.githubusercontent.com/assets/7022869/12004752/3191c1b4-ab39-11e5-92d1-3871e4e9c8e7.png)

**Comment by esdoppio** [comment] 2016-06-05 02:03
The problem lies in `'.tree-view .file .name[data-name$=\\.md]'`.

@mnquintana Is there a way to select an element that has a specific descendant in the `itemsBySelector`?

**Comment by lee-dohm** [comment] 2016-06-05 06:39
This is a duplicate of https://github.com/atom/tree-view/issues/248.

**Closed by lee-dohm** 2016-06-05 06:39 UTC
Labels: beginner, bug

**Comment by esdoppio** [comment] 2016-06-05 06:53
@lee-dohm But it looks like the problem isn't caused by the `tree-view` package.

**Comment by lee-dohm** [comment] 2016-06-05 06:56
The clickable area of the tree view item is governed by the tree-view package. So this is completely under the control of the tree-view package. That's why this is a duplicate.

**Comment by esdoppio** [comment] 2016-06-05 07:11
True, couldn't find a way to solve this without changing the output from `tree-view`.
