### ISSUE TITLE
Scroll Sync preview

### ISSUE THREAD

**Issue by pabloab** [atom/markdown-preview#417] opened 2016-08-24 15:46 UTC
As in dillinger.io Scroll Sync option, it would be great to have te possibility to sync source file with the preview.

**Comment by lee-dohm** [comment] 2016-08-27 04:40
This is a duplicate of https://github.com/atom/markdown-preview/issues/24. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-08-27 04:40 UTC
