### ISSUE TITLE
can markdown-preview add a option auto scroll with cursor?

### ISSUE THREAD

**Issue by gdbdzgd** [atom/markdown-preview#274] opened 2015-07-09 02:37 UTC
no is like this:
![screenshot-not-scall](https://cloud.githubusercontent.com/assets/734458/8586851/427d171e-2626-11e5-9f2b-81a1537a8b19.png)

i think  add a option can auto scroll with cursor like this is better!
![screenshot-5](https://cloud.githubusercontent.com/assets/734458/8586858/698465ec-2626-11e5-8154-c9e1b1608403.png)

**Comment by mnquintana** [comment] 2015-07-09 02:40
This is a duplicate of https://github.com/atom/markdown-preview/issues/24 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-09 02:40 UTC
