### ISSUE TITLE
 HTML style block in markdown applies to Atom chrome/UI.

### ISSUE THREAD

**Issue by marv3lls** [atom/markdown-preview#540] opened 2018-06-21 03:46 UTC
### Prerequisites

* [😭] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

HTML style block in markdown applies to Atom chrome/UI.

### Steps to Reproduce

Open Markdown Preview. Put:
```

<style>
* {
	font-family: 'inconsolata-g for powerline',verdana,arial,sans-serif;
	font-size:32px;
	color: #2b2b2b;
}
strong {
	color:#2b2b2b;
	font-family:'inconsolata-g for powerline',monospace;
	line-height:7px;
	text-decoration:none;
	font-size:16px;
}
</style>
```
in a markdown file.

**Expected behavior:** I expect the preview window to get all those styles.

**Actual behavior:** It applied to all my chrome.

**Reproduces how often:** Only tested once.

### Versions

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 2.7.15
git 2.17.1

### Additional Information

I don't have a lot of time to experiment, this is just a quick issue.

**Comment by rsese** [comment] 2018-06-21 16:58
Thanks for the report!

This looks like a duplicate of https://github.com/atom/markdown-preview/issues/276 so you can subscribe there if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-06-21 16:58 UTC
