### ISSUE TITLE
Synchronous scrolling

### ISSUE THREAD

**Issue by renkun-ken** [atom/markdown-preview#223] opened 2015-03-26 11:23 UTC
Is it possible to implement synchronous scrolling, i.e. when I scroll markdown source document, the preview should scroll too, and (better) vice versa?

**Comment by thomasjo** [comment] 2015-03-26 11:29
Duplicate of https://github.com/atom/markdown-preview/issues/24.

**Closed by thomasjo** 2015-03-26 11:29 UTC
