### ISSUE TITLE
Adding style caused style changes to Atom window as well. 

### ISSUE THREAD

**Issue by sharynneazhar** [atom/markdown-preview#419] opened 2016-08-27 03:39 UTC
On line 19, I added a border style to div tags. It added borders to div tags of my Atom program too. 

<img width="1084" alt="screen shot 2016-08-26 at 10 32 10 pm" src="https://cloud.githubusercontent.com/assets/10108593/18024944/dddf226c-6bdd-11e6-95ba-f916de80e325.png">

**Comment by lee-dohm** [comment] 2016-08-27 04:35
This is a duplicate of https://github.com/atom/markdown-preview/issues/276. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-08-27 04:35 UTC
