### ISSUE TITLE
Cross-reference is not working

### ISSUE THREAD

**Issue by jvtrudel** [atom/markdown-preview#469] opened 2017-02-28 17:57 UTC
According to [this stackoverflow post](http://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown). It should be possible to use cros-reference to link information inside a document. 

For example example (from the accepted answer):

>     Take me to [pookie](#pookie)
>
>should be the correct markdown syntax to jump to the anchor point named pookie.
>
>To insert an anchor point of that name use HTML:
>
>    \<a name="pookie">\</a>
>
>Markdown doesn't seem to mind where you put the anchor point. A useful place to put it is in a header.

This feature does not work in markdown-preview.

Is it possible to add this feature? And if yes, how should I do to implement it?

**Comment by 50Wliu** [comment] 2017-02-28 17:59
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #314. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-28 17:59 UTC

**Comment by jvtrudel** [comment] 2017-02-28 19:07
ok. Sorry, did don't found this issue in my research. I'll follow the proress their.
