### ISSUE TITLE
Synchronize preview with open Markdown file

### ISSUE THREAD

**Issue by asbjornu** [atom/markdown-preview#363] opened 2016-01-28 09:52 UTC
This can be solved in several ways, but the core problem seems to be that the preview is opened in a disconnected tab. If I have two Markdown files; `one.md` and `two.md`, if I open preview for `one.md` and then open `two.md`, the tab that previews `one.md` won't change. If I open a preview for `two.md`, it will open a new tab alongside the already opened tab for `one.md`.

Instead, I would like the preview tab to either:

1. switch which file it previews as I open different `.md` files
2. be "attached" to the tab of the file it previews, such that the tab is split vertically in half with the text on the left hand side and the preview on the right hand side.

I prefer option 2, but would be content with option 1 if it is simpler.

**Comment by lee-dohm** [comment] 2016-01-28 19:08
This is essentially a duplicate of #48, though definitely much more clearly described. Please subscribe there for updates.

**Closed by lee-dohm** 2016-01-28 19:08 UTC
