### ISSUE TITLE
I'm curious Why it can't show Chinese correctly?

### ISSUE THREAD

**Issue by yinwoods** [atom/markdown-preview#246] opened 2015-04-26 17:55 UTC
I use markdown-preview in the atom editor, can you help me solve this problem?

**Comment by lee-dohm** [comment] 2015-04-26 22:40
You probably need to style it to use a font that includes Chinese glyphs. There is a great post on [Discuss](https://discuss.atom.io), the official Atom message board, about how to fix this kind of thing for Hindi on the tree view:

https://discuss.atom.io/t/unicode-font-support-in-treeview/16310/4?u=leedohm

**Comment by lee-dohm** [comment] 2015-04-26 22:40
Let us know if you need more help!

**Comment by 50Wliu** [comment] 2015-04-27 00:18
Duplicate of #238, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-27 00:18 UTC
Labels: question
