### ISSUE TITLE
Markdown syntax highlighter doesn't ignore code block's asterisks

### ISSUE THREAD

**Issue by cbowns** [atom/markdown-preview#265] opened 2015-06-27 00:22 UTC
Markdown parser reads italics from "*" in code blocks but shouldn't.

My Markdown READMEs are mostly italicized these days:

![](https://cloudup.com/files/iWKHthnh4-w/download)

Even though this is a code block (indented by a tab or four spaces), the in-file syntax highlighter doesn't know it.

## Repro Steps

1. Put some code with a "*" in a markdown file. Here's some simple Markdown for you:

```
Hello everyone! Here's some code:

    NSString *title = [NSString stringWithString:@"Hi"];

Anyways, hope your text looks normal!
```

2. Open this in Atom.

## Versions

* **Atom:**       1.0.0
* **Atom-Shell:** 0.22.3
* **OS:**         Mac OS X 10.10.3

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by leipert** [comment] 2015-09-04 16:00
@cbowns 
This package actually does no syntax highlighting, the package you are looking for is language-gfm and the issue is described here:
https://github.com/atom/language-gfm/issues/44

You can try my package [language-pfm](https://atom.io/packages/language-pfm)
which renders your example fine:
![screen shot 2015-09-04 at 17 59 59](https://cloud.githubusercontent.com/assets/2906107/9688329/cb37669c-532e-11e5-8652-f45fa0731cf6.png)

**Comment by 50Wliu** [comment] 2015-09-04 19:39
Thanks, @leipert!  Closing as a duplicate of atom/language-gfm#44.

**Closed by 50Wliu** 2015-09-04 19:39 UTC
