### ISSUE TITLE
not using ctrl-shift-m 

### ISSUE THREAD

**Issue by JPomichael** [atom/markdown-preview#287] opened 2015-08-14 15:04 UTC
not using ctrl-shift-m in windows 8.1

**Comment by kevinsawicki** [comment] 2015-08-14 22:02
Can you open the keybinding resolver using `ctrl-.` and then press `ctrl-shift-m` and see what command is being triggered for that keybinding?

Also, can you reproduce it safe mode? Completely quit Atom and then run `atom --safe` from the terminal

**Comment by JPomichael** [comment] 2015-08-15 11:36
Ok, i try. 

From  iPhone

**Comment by varunyellina** [comment] 2015-08-21 11:50
I'm unable to activate the preview using `ctrl-shift-m` on OSX using **Atom 1.0.7** and **markdown-preview 0.150.0**.

On the contrary using the menu item `Packages > Mardown Preview > Toggle Preview` works without issue.

**Comment by varunyellina** [comment] 2015-08-21 11:55
Update: I just used the Key Binding Resolver on Mac using `Cmd - .`. I've the Emmet package installed which is overwriting `ctrl-shift-M`

Since this not technically an issue with your package, could you suggest me on how to solve this. I would like to keep the emmet shortcuts unchanged.
Thank you.

Regards
Varun

**Comment by XiaoSK** [comment] 2015-11-06 07:30
Many thanks to @varunyellina . It works. But I preferred binding another key to `'markdown-preview:toggle'` instead of `'ctrl-shift-M'`.

**Comment by 50Wliu** [comment] 2015-11-06 14:39
Hey @JPomichael, if the steps listed by @varunyellina didn't work for you, please comment here.  Otherwise, I'm closing this.

**Closed by 50Wliu** 2015-11-06 14:39 UTC
Labels: more-information-needed
