### ISSUE TITLE
If last cell doesn't have data it does not render

### ISSUE THREAD

**Issue by fcrespo82** [atom/markdown-preview#258] opened 2015-06-02 22:37 UTC
Hi, I found a bug in markdown table rendering.

It does not renders the last cell if it's empty.

Atom version: 0.204.0
markdown-preview version: 0.150.0
OS: Ubuntu 14.04

![table_formatted](https://cloud.githubusercontent.com/assets/462171/7948769/8611a0d4-095d-11e5-8e13-9056333dbb11.png)

**Comment by izuzak** [comment] 2015-06-03 06:38
Thanks for the report, @fcrespo82 -- looks like a duplicate of https://github.com/atom/markdown-preview/issues/206, which should have a better title. I'll close this and update the title on the other issue, so please follow that for updates.

**Closed by izuzak** 2015-06-03 06:38 UTC
