### ISSUE TITLE
 Chinese characters appear as squares

### ISSUE THREAD

**Issue by electricface** [atom/markdown-preview#285] opened 2015-08-11 07:25 UTC
Chinese characters appear as squares

![20150811152326](https://cloud.githubusercontent.com/assets/3241440/9192355/f5d85ba4-403c-11e5-88db-2742c2fde030.png)

**Comment by kurtzhong** [comment] 2015-09-16 08:33
Any updates on this issues, this make me to write documentations in English, but sometimes I have to read/write in Chinese.

**Comment by mnquintana** [comment] 2015-09-16 13:08
This looks like a duplicate of https://github.com/atom/markdown-preview/issues/238 – closing this out in favor of that issue.

**Closed by mnquintana** 2015-09-16 13:08 UTC
