### ISSUE TITLE
`Enter` key cannot use after markdown doc previewed

### ISSUE THREAD

**Issue by 1ternal** [atom/markdown-preview#172] opened 2015-01-12 08:49 UTC
When I previewed my doc then close preview pane, I cannot use `Enter` key in the .md file.
I'v to reopen atom editor to use `enter` key with this md file.

There was no problem before upgrade to atom version 0.169

I'm using aluratek brand kvm switch, Mac Yosemite. I' not sure is this related.

**Comment by benogle** [comment] 2015-01-12 18:27
Do you have the emmet package installed?

**Comment by 1ternal** [comment] 2015-01-13 06:47
yes, I've install Emmet version 2.3.0;
and after disable emmet, everything works fine! :smile:

**Comment by lee-dohm** [comment] 2015-01-13 08:27
Closing as duplicate of emmetio/emmet-atom#186.

**Closed by lee-dohm** 2015-01-13 08:27 UTC
Labels: more-information-needed
