### ISSUE TITLE
When converted markdown to html, the relative paths are changed.

### ISSUE THREAD

**Issue by ruijun** [atom/markdown-preview#404] opened 2016-06-16 07:28 UTC
e.g. `![img](pic/test.png) `
It is OK in the markdown preview, but when I export the html file, the image links are not working. 

As when I check out the html code, it all automatically add a absolute link like:
```
<img src="/Users/ruijun/pic/test.png" alt="">
```
This is totally useless as when I send the whole folder to others. 

**Why not just remain the relative paths in the HTML code?**

**Comment by 50Wliu** [comment] 2016-06-16 13:19
This is a duplicate of #146 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-16 13:19 UTC

**Comment by ruijun** [comment] 2016-06-16 13:36
@50Wliu As  #146  say, it is only use absoluted path?
