### ISSUE TITLE
Blockquote overflow scrolling vertically and horizontally.

### ISSUE THREAD

**Issue by ProLoser** [atom/markdown-preview#381] opened 2016-03-10 21:49 UTC
If a huge blockquote is rendered, it scrolls vertically as well as horizontally. I think it should be set to only scroll horizontally.
![0hrcpmcmh6](https://cloud.githubusercontent.com/assets/67395/13685765/05ad6624-e6c7-11e5-8878-091ba35ed642.gif)

**Comment by lee-dohm** [comment] 2016-03-11 00:13
May be related to https://github.com/atom/markdown-preview/issues/245. Can you turn off "Scroll Past End" in your settings and see if that fixes it?

**Comment by pierregodard** [comment] 2016-07-28 14:43
@lee-dohm your suggestion to turn off `Scroll Past End` actually solves the problem on my end for those code blocks (but then you also can't "scroll past end" anywhere anymore, which is problematic since it's quite nice when editing the end of a file)

**Comment by marcofugaro** [comment] 2017-03-27 10:34
`Scroll past end` should be always disabled in blockquotes

**Comment by 50Wliu** [comment] 2017-03-28 13:40
Closing as a duplicate of #245.

**Closed by 50Wliu** 2017-03-28 13:40 UTC
