### ISSUE TITLE
CSS Injection

### ISSUE THREAD

**Issue by mpvillafranca** [atom/markdown-preview#318] opened 2015-10-19 11:48 UTC
If you write something like

```
<style>
*{
visibility:hidden;
}
</style>
```

this affects to Atom GUI too, maybe it's something you could fix... or maybe not...

**Comment by 50Wliu** [comment] 2015-10-19 11:50
Duplicate of #276, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-19 11:50 UTC
