### ISSUE TITLE
Preview scrolls back to the middle of the document

### ISSUE THREAD

**Issue by knzudgt** [atom/markdown-preview#476] opened 2017-03-24 20:05 UTC
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whenever I add text in the editor, the preview, instead of showing the last lines of code, auto scrolls back to the middle of the page, so that having a live update is useless. Thus I have to scroll down to see the preview of last added text. Am I the only one experiencing this issue? Is there any way to change or fix  this behaviour?

### Steps to Reproduce

1. Open attached file and open markdown preview
2. Try to add text to the editor and click enter 
3. See how the preview pane scrolls back

**Expected behavior:** [What you expect to happen]

The preview pane should synchronize with the editor, or at least do not move from the cursor position. 

**Actual behavior:** [What actually happens]

The preview pane auto scrolls back out of sync with the editor

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS: Ubuntu 14.04 LTS regularly updated
[extract.txt](https://github.com/atom/markdown-preview/files/869229/extract.txt)

@rsese

**Comment by rsese** [comment] 2017-03-24 20:36
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by knzudgt** [comment] 2017-03-24 20:48
@rsese would you suggest to edit my original message or open a new more complete issue?

**Comment by rsese** [comment] 2017-03-24 20:58
Feel free to just edit the issue body @knzudgt, thanks!

**Comment by rsese** [comment] 2017-03-29 20:02
Thanks for updating the issue body :v:

I tried to reproduce but didn't see the same behavior - after entering some text in the middle of the file and hitting <kbd>Enter</kbd>, the preview didn't scroll.

I'm on macOS however, so I'll try with Ubuntu later.

**Comment by knzudgt** [comment] 2017-03-30 08:36
@rsese The issue happens when I _append_ text, that is when I add text at the bottom of the file. The preview does not stay at the bottom (showing what I have just typed) but scrolls back. This happens both in live update (which I do not use for large files) **and** when live update is unchecked.

![screenshot1](https://cloud.githubusercontent.com/assets/15718033/24495060/41c84bbe-1534-11e7-850b-6e23c191a829.png)

**Comment by rsese** [comment] 2017-03-31 03:02
Ohhh gotcha, thanks for clarifying @knzudgt :v:

I do see this behavior and after poking around a bit, it looks like it's a dupe of https://github.com/atom/markdown-preview/issues/370 (best described in this comment /cc https://github.com/atom/markdown-preview/issues/370#issuecomment-191697120)?  Going to go ahead and close this and you can subscribe in that issue but if I'm mis-understanding anything, please let me know.

**Closed by rsese** 2017-03-31 03:02 UTC
Labels: needs-reproduction
