### ISSUE TITLE
Scroll Past End affects code blocks

### ISSUE THREAD

**Issue by ibnesayeed** [atom/markdown-preview#214] opened 2015-03-11 17:15 UTC
Enabling "Scroll Past End" config in the mail editor settings affects code blocks in Markdown Preview as well. Say, there are 10 lines of code in a markdown file and the mail Atom editor has "Scroll Past End" config enabled, while scrolling the preview, rendered code block will also be scrollable, enough to scroll up all the 10 lines of code. This is often very frustrating experience.

**Comment by 50Wliu** [comment] 2015-03-11 18:25
Duplicate of #209, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-11 18:25 UTC
