### ISSUE TITLE
[Feature Request] Scroll the Preview in sync with Editor

### ISSUE THREAD

**Issue by Netherdrake** [atom/markdown-preview#331] opened 2015-11-07 11:05 UTC
Mou does it, and its by far its best feature.
http://25.io/mou/

**Comment by thomasjo** [comment] 2015-11-07 11:39
This is a duplicate of #24.

**Closed by thomasjo** 2015-11-07 11:39 UTC

**Comment by Netherdrake** [comment] 2015-11-07 11:47
Locked and ignored. I guess markdown-preview won't do. Thanks anyway for all the hard work you guys have put into Atom, its a pretty cool editor.
