### ISSUE TITLE
hyperlink including right parenthesis will be omitted

### ISSUE THREAD

**Issue by FrancisHe** [atom/markdown-preview#415] opened 2016-08-17 04:58 UTC
content:
```
[Join (SQL)](https://en.wikipedia.org/wiki/Join_(SQL))
```

preivew:
```
Join (SQL))
```

the link:
```
https://en.wikipedia.org/wiki/Join_(SQL
```
the right parenthesis is omitted.

**Comment by 50Wliu** [comment] 2016-08-17 13:20
This is a duplicate of #374 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-17 13:20 UTC
