### ISSUE TITLE
Vertical split plane

### ISSUE THREAD

**Issue by svoop** [atom/markdown-preview#229] opened 2015-04-01 09:35 UTC
A very nice extension!

However, it would be very cool, if there was a setting to preview in a vertical split plane (down) instead of the default horizontal (right) one.

**Comment by izuzak** [comment] 2015-04-01 11:44
Looks like a duplicate of https://github.com/atom/markdown-preview/issues/99.

**Closed by izuzak** 2015-04-01 11:44 UTC
