### ISSUE TITLE
Image is not updated in preview

### ISSUE THREAD

**Issue by thellef** [atom/markdown-preview#376] opened 2016-02-22 13:25 UTC
If you change an image after the link is saved in a Markdown file(.md), the preview does not reflect this. Same happens if you change the link to another file. The first file is shown until you exit Atom and start it again,

**Comment by 50Wliu** [comment] 2016-02-22 13:36
This is a duplicate of #207 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-22 13:36 UTC
