### ISSUE TITLE
Failed to load the markdown-preview package

### ISSUE THREAD

**Issue by Ayaminn** [atom/markdown-preview#235] opened 2015-04-05 03:11 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.146.0

### Stack Trace

Failed to load the markdown-preview package

```
At Unrecognised input in /Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/styles/markdown-preview.less:415:2

LessError: Unrecognised input
  at /Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/styles/markdown-preview.less:415:2
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-paths, v1.0.2
highlight-selected, v0.9.1

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-07-20 23:55
This looks like an issue with a corrupt update that was hopefully fixed by using asar in version 0.193 and above, closing this out.

**Closed by kevinsawicki** 2015-07-20 23:55 UTC

**Comment by rubencaro** [comment] 2015-11-03 13:17
Should it be reopened?

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: "Fedora release
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.154.0


### Stack Trace

Failed to load the markdown-preview package

```
At Recursive variable definition for @syntax-background-color in /usr/share/atom/resources/app.asar/node_modules/markdown-preview/styles/markdown-preview-default.less:13:7

LessError: Recursive variable definition for @syntax-background-color
  at /usr/share/atom/resources/app.asar/node_modules/markdown-preview/styles/markdown-preview-default.less:13:7
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "kuali-dark-syntax"
    ],
    "projectHome": "/home/ruben/Documentos",
    "followSymlinks": true,
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
git-diff-details, v0.21.0
highlight-selected, v0.10.1
kuali-dark-syntax, v1.3.0
minimap, v4.16.0
minimap-autohide, v0.10.1
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
up2date, v0.0.7

# Dev
No dev packages
```

**Comment by klorenz** [comment] 2015-11-06 01:18
I am having the same issue.

It is a bit confusing, because the atom error notification makes me think that this issue is already reported  (well it is) and worked on, but it is closed for an earlier version of atom, so no one works on it.
