### ISSUE TITLE
Live update makes the page scroll

### ISSUE THREAD

**Issue by justineakehurst** [atom/markdown-preview#362] opened 2016-01-20 23:04 UTC
I'm trying to edit my markdown page, and when I do, the preview pane will scroll to a point where I can't see my live changes. I'd like that pane to just stay scrolled to the point where I put it, or to scroll the pane to the point where my changes appear in the middle of the pane, not scrolled out of view.

**Comment by eigan** [comment] 2016-01-22 08:31
Check out the plugin [markdown-scroll-sync](https://atom.io/packages/markdown-scroll-sync) as mentioned in issue #24 :)

**Comment by chemzqm** [comment] 2016-01-31 15:53
Got the same issue, it disappointed me a lot.

**Comment by lee-dohm** [comment] 2016-02-01 19:57
This is a duplicate of https://github.com/atom/markdown-preview/issues/178. Please update that Issue with the following information:

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

I haven't reopened that bug yet because I can't reproduce this behavior using Atom v1.4.1 on Mac OS X 10.11.3.

**Closed by lee-dohm** 2016-02-01 19:57 UTC
