### ISSUE TITLE
Preview of code snippet looks out of whack

### ISSUE THREAD

**Issue by joesustaric** [atom/markdown-preview#360] opened 2016-01-14 04:52 UTC
Hi there,

Here is a screenshot of an issue I just noticed. 
The A should be centered at the top. 
It is displayed correctly if I push that and view on github.
Thanks
![screen shot 2016-01-14 at 3 47 55 pm](https://cloud.githubusercontent.com/assets/199240/12316067/9b157d72-bad6-11e5-82dc-30ec9b818ca0.png)

**Comment by joesustaric** [comment] 2016-01-14 04:53
Atom v 1.4.0

**Comment by lee-dohm** [comment] 2016-01-14 06:32
Confirmed using Atom v1.4.0 on Mac OS X 10.11.2.

**Comment by joesustaric** [comment] 2016-01-14 07:29
Yup sorry forgot to mention I'm also on a Mac OS X 10.11.2
Thanks

**Comment by lee-dohm** [comment] 2016-01-14 16:20
@simurai Is this something that can be fixed with CSS? Or is this a code problem?

**Comment by simurai** [comment] 2016-01-15 00:49
It looks like the white space `<span>`s are missing for the first line.

Tested with:

```
    A
   B
  C
 D
E
```

![screen shot 2016-01-15 at 9 43 09 am](https://cloud.githubusercontent.com/assets/378023/12342314/d48f0e4c-bb6c-11e5-942e-9a5c019a0ac5.png)

Not sure where/why they got dropped, since the code blocks get rendered with `<atom-text-editor>`s.

**Comment by lee-dohm** [comment] 2016-01-15 00:51
Thanks @simurai! I'll follow up.

**Comment by chrahunt** [comment] 2016-03-06 16:39
As mentioned in the issue on markdown-preview-plus, it looks like fixing this should just be a matter of removing `trim()` [here](https://github.com/atom/markdown-preview/blob/master/lib/renderer.coffee#L122).

**Closed** 2016-08-30 21:24 UTC
Labels: bug
