### ISSUE TITLE
Style-tags appear to leak into Atom

### ISSUE THREAD

**Issue by RadiationG0D** [atom/markdown-preview#326] opened 2015-11-03 16:47 UTC
I was using Atom to preview a very simple piece of html when I noticed that the following code:
`<style>
body {
   text-align: center;
}
</style>`

did not just affect my preview but the entire atom editor. I have attached two images, displaying the "before" and "after" cases.

Note the shift in position of the directory tree and that the contents of the "settings"-tab (not seen in the images) was also affected

**EDIT**
The problem occurs when I open the file in preview mode and goes away when I close the preview

**EDIT2**
Problem occured in Windows 10 with Atom 1.1.0 and markdown-preview 0.154.0

![atom_nopreview](https://cloud.githubusercontent.com/assets/2656517/10914264/de7ec388-8251-11e5-979e-ee8c9c2f3bcd.PNG)

![atom_preview](https://cloud.githubusercontent.com/assets/2656517/10914263/de5cf7c6-8251-11e5-8aac-89e047b9f21a.PNG)

**Comment by 50Wliu** [comment] 2015-11-03 16:55
Duplicate of #276, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-03 16:55 UTC
