### ISSUE TITLE
I have installed it but its not opening

### ISSUE THREAD

**Issue by pitops** [atom/markdown-preview#284] opened 2015-08-09 12:12 UTC
I am on a macbook pro v10.10.4 15inch latest model.

I click command+shift+m while i am in the readme.md file but its not opening anything

note that it works if i go manually in packages-> markdown preview-> and Toggle it ON

**Comment by mnquintana** [comment] 2015-08-09 12:23
The keybinding is <kbd>Ctrl-Shift-M</kbd>, not <kbd>Cmd-Shift-M</kbd> - does that work for you?

**Comment by pitops** [comment] 2015-08-09 12:28
i tried that as well, it doesn't work.

**Comment by mnquintana** [comment] 2015-08-09 13:03
Can you open the keybinding resolver with <kbd>Cmd-.</kbd>, enter <kbd>Ctrl-Shift-M</kbd>, and take a screenshot of what you see?

**Comment by pitops** [comment] 2015-08-09 13:17
Hmm it seems is has something to do with Emmet?
<img width="1440" alt="screen shot 2015-08-09 at 16 14 31" src="https://cloud.githubusercontent.com/assets/9624361/9155005/f4af5264-3eb1-11e5-817f-b4864e1035ad.png">

**Comment by mnquintana** [comment] 2015-08-09 13:25
Thanks for the update! Looks like a duplicate of https://github.com/atom/markdown-preview/issues/280.

**Closed by mnquintana** 2015-08-09 13:25 UTC
Labels: more-information-needed
