### ISSUE TITLE
Single asterisks cause text to be in italics

### ISSUE THREAD

**Issue by tterranigma** [atom/markdown-preview#495] opened 2017-08-29 15:35 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Text like that contains a wildcard '*' is printed as italics.

### Steps to Reproduce

1. Create a new document and set the language to 'Github Markdown'
2. Type: `Lines containing wildcards like '*.jpg' should be not in italics`

**Expected behavior:** [What you expect to happen]
The text should be normal.

**Actual behavior:** [What actually happens]
The text after the asterisk is printed in italics

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions
Atom    : 1.18.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0

apm  1.18.5
npm  5.3.0
node 8.4.0 x64
python 2.7.13
git 2.14.1

Arch linux latest

**Comment by rsese** [comment] 2017-08-30 04:43
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-gfm/issues/44. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-30 04:43 UTC
