### ISSUE TITLE
Code block with an extra line

### ISSUE THREAD

**Issue by chimit** [atom/markdown-preview#507] opened 2017-10-26 08:37 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom adds an extra line into Markdown code blocks:

![2017-10-26 16 33 32](https://user-images.githubusercontent.com/839349/32042817-74fa8380-ba6b-11e7-83c0-b2f35cde1fd4.png)

### Versions

Atom version 1.21.1
Markdown Preview version 0.159.15

**Comment by Ben3eeE** [comment] 2017-10-26 08:39
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/markdown-preview/issues/479. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-10-26 08:39 UTC
Labels: duplicate
